language: r
sudo: false
cache: packages

r:
 - release
 - devel
 - oldrel

r_github_packages:
  - gaborcsardi/debugme

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
